name: typescript

on:
  push:
    branches: ["main"]
    paths:
      - "typescript/**"
  pull_request:
    branches: ["main"]
    paths:
      - "typescript/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup pnpm
        uses: pnpm/action-setup@v2.4.0

      - name: Build
        run: pnpm run dev
        working-directory: ./typescript
